spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}?sslmode=require
  flyway:
    baseline-on-migrate: true
    baseline-version: "017"

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
